name: bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: registry.gitlab.com/derekjchow/bazel-rocky-8:main

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: bazel build //hdl/chisel/src/coralnpu:rvv_core_mini_axi_cc_library_emit_verilog

